name: 'Terraform'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Deployment'
    runs-on: ubuntu-latest
    environment: dev

    env:
      ARM_CLIENT_ID: ${{ secrets.AZ_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZ_SECRET_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZ_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZ_TENANT_ID }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Terraform Format
        uses: hashicorp/terraform-github-actions@v2.0.3
        with:
          tf_actions_version: 1.5.7
          tf_actions_subcommand: 'fmt'
          tf_actions_working_dir: './terrform'

      - name: Terraform Init
        uses: hashicorp/terraform-github-actions@v2.0.3
        with:
          tf_actions_version: 1.5.7
          tf_actions_subcommand: 'init'
          tf_actions_working_dir: './terrform'

      - name: Terraform Validate
        uses: hashicorp/terraform-github-actions@v2.0.3
        with:
          tf_actions_version: 1.5.7
          tf_actions_subcommand: 'validate'
          tf_actions_working_dir: './terrform'

      - name: Terraform Plan
        uses: hashicorp/terraform-github-actions@v2.0.3
        with:
          tf_actions_version: 1.5.7
          tf_actions_subcommand: 'plan'
          tf_actions_working_dir: './terrform'

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master'
        uses: hashicorp/terraform-github-actions@v2.0.3
        with:
          tf_actions_version: 1.5.7
          tf_actions_subcommand: 'apply'
          tf_actions_working_dir: './terrform'
